name: study_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  #image_path: "assets/icon/icon.png"
  image_path_android: "assets/ify_logo_710x599.png"
  image_path_ios: "assets/ify_logo_1024x1024.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/ify_logo_432x432.png"
  adaptive_icon_monochrome: "assets/ify_logo_432x432.png"
  web:
    generate: true
    image_path: "assets/ify_logo_1024x1024.png"
    #background_color: "#hexcode"
    #theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/ify_logo_1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/ify_logo_1024x1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/ify_logo.png
    - assets/ify_logo_710x599.png
    - assets/ify_logo_1024x1024.png
    - assets/ify_logo_432x432.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
